# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
