# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='informacionAdicional',
            new_name='datos_cliente',
        ),
    ]
